2025-03-29 16:31:16,303 - INFO - Start polling
2025-03-29 16:31:16,355 - ERROR - Ошибка поддержания сессии для +79699304873: 
2025-03-29 16:31:21,895 - ERROR - Ошибка переподключения +79699304873: database is locked
2025-03-29 16:31:21,895 - ERROR - Не удалось переподключить +79699304873: database is locked
2025-03-29 16:31:22,267 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:31:22,817 - INFO - Update id=821254068 is handled. Duration 407 ms by bot id=7597499330
2025-03-29 16:31:27,919 - INFO - Update id=821254069 is handled. Duration 141 ms by bot id=7597499330
2025-03-29 16:31:28,876 - INFO - Update id=821254070 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 16:31:29,604 - INFO - Update id=821254071 is handled. Duration 172 ms by bot id=7597499330
2025-03-29 16:31:48,593 - INFO - Update id=821254074 is handled. Duration 422 ms by bot id=7597499330
2025-03-29 16:31:49,506 - INFO - Update id=821254075 is handled. Duration 202 ms by bot id=7597499330
2025-03-29 16:34:30,139 - INFO - Start polling
2025-03-29 16:34:30,537 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:34:37,725 - INFO - Update id=821254077 is handled. Duration 390 ms by bot id=7597499330
2025-03-29 16:34:39,083 - INFO - Update id=821254078 is handled. Duration 155 ms by bot id=7597499330
2025-03-29 16:34:39,724 - INFO - Update id=821254079 is handled. Duration 141 ms by bot id=7597499330
2025-03-29 16:34:40,701 - INFO - Update id=821254080 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 16:34:46,467 - INFO - Попытка добавить группу: https://t.me/Testitos123
2025-03-29 16:34:46,467 - INFO - Данные группы: {'id': 6929487645374662114, 'title': 'Группа @Testitos123', 'username': 'Testitos123', 'invite_link': 'https://t.me/Testitos123'}
2025-03-29 16:36:26,158 - INFO - Start polling
2025-03-29 16:36:26,545 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:36:29,146 - INFO - Update id=821254082 is handled. Duration 390 ms by bot id=7597499330
2025-03-29 16:36:30,355 - INFO - Update id=821254083 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 16:36:34,053 - INFO - Update id=821254084 is handled. Duration 172 ms by bot id=7597499330
2025-03-29 16:36:35,466 - INFO - Добавление группы: https://t.me/Testitos123
2025-03-29 16:36:35,466 - INFO - Сформированные данные: {'id': 5823541291229635262, 'title': 'Группа @Testitos123', 'username': 'Testitos123', 'invite_link': 'https://t.me/Testitos123'}
2025-03-29 16:36:35,466 - ERROR - Ошибка сохранения: GroupManager.add_group() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "C:\Users\Sat\Desktop\Bot7k\bot.py", line 580, in process_add_group
    saved = await group_manager.add_group(**group_data)
TypeError: GroupManager.add_group() got an unexpected keyword argument 'id'
2025-03-29 16:36:35,610 - INFO - Состояние формы сброшено
2025-03-29 16:36:35,611 - INFO - Update id=821254085 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 16:47:29,449 - ERROR - Error connecting +79699304873: RetryError[<Future at 0x17f6e925f90 state=finished raised AssertionError>]
2025-03-29 16:47:29,464 - INFO - Start polling
2025-03-29 16:47:29,894 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:47:30,473 - INFO - Update id=821254086 is handled. Duration 453 ms by bot id=7597499330
2025-03-29 16:47:33,031 - INFO - Update id=821254087 is handled. Duration 155 ms by bot id=7597499330
2025-03-29 16:47:34,332 - INFO - Update id=821254088 is handled. Duration 155 ms by bot id=7597499330
2025-03-29 16:47:36,044 - INFO - Adding group: https://t.me/Testitos123
2025-03-29 16:47:36,044 - INFO - Generated data: {'id': 1348754402239123266, 'title': 'Группа @Testitos123', 'username': 'Testitos123', 'invite_link': 'https://t.me/Testitos123'}
2025-03-29 16:47:36,044 - ERROR - Save error: GroupManager.add_group() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "C:\Users\Sat\Desktop\Bot7k\bot.py", line 642, in process_add_group
    saved = await group_manager.add_group(**group_data)
TypeError: GroupManager.add_group() got an unexpected keyword argument 'id'
2025-03-29 16:47:36,364 - INFO - Form state cleared
2025-03-29 16:47:36,364 - INFO - Update id=821254089 is handled. Duration 312 ms by bot id=7597499330
2025-03-29 16:47:39,616 - ERROR - Session error for +79699304873: RetryError[<Future at 0x17f6e9aceb0 state=finished raised AssertionError>]
2025-03-29 16:47:55,364 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x17f6e9ad450 state=finished raised AssertionError>]
2025-03-29 16:47:55,364 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x17f6e9ad450 state=finished raised AssertionError>]
2025-03-29 16:52:39,410 - ERROR - Error connecting +79699304873: RetryError[<Future at 0x2808b137670 state=finished raised AssertionError>]
2025-03-29 16:52:39,411 - INFO - Start polling
2025-03-29 16:52:39,856 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:52:40,488 - INFO - Update id=821254090 is handled. Duration 500 ms by bot id=7597499330
2025-03-29 16:52:48,440 - INFO - Update id=821254091 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 16:52:49,574 - ERROR - Session error for +79699304873: RetryError[<Future at 0x2808b198c40 state=finished raised AssertionError>]
2025-03-29 16:52:59,297 - INFO - Группы успешно сохранены
2025-03-29 16:53:05,274 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x2808b19aad0 state=finished raised AssertionError>]
2025-03-29 16:53:05,275 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x2808b19aad0 state=finished raised AssertionError>]
2025-03-29 16:53:19,811 - INFO - Update id=821254092 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 16:53:21,028 - INFO - Update id=821254093 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 16:53:22,623 - INFO - Update id=821254094 is handled. Duration 765 ms by bot id=7597499330
2025-03-29 16:53:24,108 - INFO - Update id=821254095 is handled. Duration 157 ms by bot id=7597499330
2025-03-29 16:53:24,744 - INFO - Update id=821254096 is not handled. Duration 15 ms by bot id=7597499330
2025-03-29 16:53:29,304 - INFO - Группы успешно сохранены
2025-03-29 16:53:59,336 - INFO - Группы успешно сохранены
2025-03-29 16:54:29,368 - INFO - Группы успешно сохранены
2025-03-29 16:54:59,386 - INFO - Группы успешно сохранены
2025-03-29 16:55:29,386 - INFO - Группы успешно сохранены
2025-03-29 16:55:59,412 - INFO - Группы успешно сохранены
2025-03-29 16:56:28,516 - ERROR - Error connecting +79699304873: RetryError[<Future at 0x1aa445a5e70 state=finished raised AssertionError>]
2025-03-29 16:56:28,516 - INFO - Start polling
2025-03-29 16:56:28,908 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 16:56:29,435 - INFO - Update id=821254097 is handled. Duration 407 ms by bot id=7597499330
2025-03-29 16:56:32,812 - INFO - Update id=821254098 is handled. Duration 234 ms by bot id=7597499330
2025-03-29 16:56:34,109 - INFO - Update id=821254099 is handled. Duration 265 ms by bot id=7597499330
2025-03-29 16:56:38,609 - ERROR - Session error for +79699304873: RetryError[<Future at 0x1aa44640b50 state=finished raised AssertionError>]
2025-03-29 16:56:44,247 - ERROR - Ошибка сохранения группы: 'GroupManager' object has no attribute 'add_group'
Traceback (most recent call last):
  File "C:\Users\Sat\Desktop\Bot7k\bot.py", line 643, in process_add_group
    saved = await group_manager.add_group(**group_data)
AttributeError: 'GroupManager' object has no attribute 'add_group'
2025-03-29 16:56:44,476 - INFO - Update id=821254100 is handled. Duration 234 ms by bot id=7597499330
2025-03-29 16:56:48,405 - INFO - Группы успешно сохранены
2025-03-29 16:56:54,388 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x1aa44641390 state=finished raised AssertionError>]
2025-03-29 16:56:54,388 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x1aa44641390 state=finished raised AssertionError>]
2025-03-29 16:57:18,435 - INFO - Группы успешно сохранены
2025-03-29 16:57:48,452 - INFO - Группы успешно сохранены
2025-03-29 16:58:18,480 - INFO - Группы успешно сохранены
2025-03-29 16:58:48,503 - INFO - Группы успешно сохранены
2025-03-29 16:59:18,506 - INFO - Группы успешно сохранены
2025-03-29 16:59:48,521 - INFO - Группы успешно сохранены
2025-03-29 17:00:18,534 - INFO - Группы успешно сохранены
2025-03-29 17:00:48,550 - INFO - Группы успешно сохранены
2025-03-29 17:01:18,565 - INFO - Группы успешно сохранены
2025-03-29 17:01:48,573 - INFO - Группы успешно сохранены
2025-03-29 17:02:04,574 - ERROR - Session error for +79699304873: RetryError[<Future at 0x1aa446784f0 state=finished raised AssertionError>]
2025-03-29 17:02:18,599 - INFO - Группы успешно сохранены
2025-03-29 17:02:20,196 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x1aa44640760 state=finished raised AssertionError>]
2025-03-29 17:02:20,196 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x1aa44640760 state=finished raised AssertionError>]
2025-03-29 17:02:48,628 - INFO - Группы успешно сохранены
2025-03-29 17:03:18,644 - INFO - Группы успешно сохранены
2025-03-29 17:03:48,654 - INFO - Группы успешно сохранены
2025-03-29 17:04:18,677 - INFO - Группы успешно сохранены
2025-03-29 17:04:48,690 - INFO - Группы успешно сохранены
2025-03-29 17:05:18,702 - INFO - Группы успешно сохранены
2025-03-29 17:05:48,723 - INFO - Группы успешно сохранены
2025-03-29 17:06:18,734 - INFO - Группы успешно сохранены
2025-03-29 17:06:48,751 - INFO - Группы успешно сохранены
2025-03-29 17:07:18,768 - INFO - Группы успешно сохранены
2025-03-29 17:07:30,389 - ERROR - Session error for +79699304873: RetryError[<Future at 0x1aa44641240 state=finished raised AssertionError>]
2025-03-29 17:07:46,076 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x1aa44641db0 state=finished raised AssertionError>]
2025-03-29 17:07:46,076 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x1aa44641db0 state=finished raised AssertionError>]
2025-03-29 17:07:48,773 - INFO - Группы успешно сохранены
2025-03-29 17:08:12,518 - ERROR - Error connecting +79699304873: RetryError[<Future at 0x1953be63ee0 state=finished raised AssertionError>]
2025-03-29 17:08:12,518 - INFO - Start polling
2025-03-29 17:08:12,935 - INFO - Run polling for bot @Testo1113_Bot id=7597499330 - 'Testo123'
2025-03-29 17:08:22,660 - ERROR - Session error for +79699304873: RetryError[<Future at 0x1953beacc70 state=finished raised AssertionError>]
2025-03-29 17:08:28,703 - INFO - Update id=821254101 is handled. Duration 390 ms by bot id=7597499330
2025-03-29 17:08:30,316 - INFO - Update id=821254102 is handled. Duration 187 ms by bot id=7597499330
2025-03-29 17:08:31,570 - INFO - Update id=821254103 is handled. Duration 202 ms by bot id=7597499330
2025-03-29 17:08:32,416 - INFO - Groups saved successfully
2025-03-29 17:08:32,599 - INFO - Update id=821254104 is handled. Duration 219 ms by bot id=7597499330
2025-03-29 17:08:38,312 - ERROR - Error reconnecting +79699304873: RetryError[<Future at 0x1953beaf6d0 state=finished raised AssertionError>]
2025-03-29 17:08:38,312 - ERROR - Failed to reconnect +79699304873: RetryError[<Future at 0x1953beaf6d0 state=finished raised AssertionError>]
2025-03-29 17:08:45,765 - INFO - Update id=821254106 is handled. Duration 187 ms by bot id=7597499330
2025-03-29 17:08:48,356 - INFO - Update id=821254107 is not handled. Duration 15 ms by bot id=7597499330
2025-03-29 17:08:50,987 - INFO - Update id=821254108 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:08:51,738 - INFO - Update id=821254109 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:08:52,232 - INFO - Update id=821254110 is not handled. Duration 15 ms by bot id=7597499330
2025-03-29 17:08:52,356 - INFO - Update id=821254111 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:08:54,643 - INFO - Update id=821254112 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 17:08:56,154 - INFO - Update id=821254113 is handled. Duration 140 ms by bot id=7597499330
2025-03-29 17:08:57,117 - INFO - Update id=821254114 is handled. Duration 202 ms by bot id=7597499330
2025-03-29 17:09:20,298 - INFO - Update id=821254115 is handled. Duration 406 ms by bot id=7597499330
2025-03-29 17:09:24,018 - INFO - Update id=821254116 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:09:25,169 - INFO - Update id=821254117 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:09:25,327 - INFO - Update id=821254118 is not handled. Duration 0 ms by bot id=7597499330
2025-03-29 17:09:25,456 - INFO - Update id=821254119 is not handled. Duration 0 ms by bot id=7597499330
